"""Course service — orchestrates LangGraph agents, manages state, grades quizzes."""

from __future__ import annotations

import asyncio
import json
import logging
from pathlib import Path
from typing import Any
from datetime import datetime, timezone

from app.agents.graphs.orchestrator import build_orchestrator_graph
from app.agents.graphs.lesson_writer import build_lesson_writer_graph
from app.agents.graphs.quiz_generator import build_quiz_generator_graph
from app.agents.graphs.tutor import build_tutor_graph
from app.models.agent import AgentStep
from app.models.course import (
    Course,
    CoursePreferences,
    Lesson,
    LessonOutline,
    Quiz,
    QuizOption,
    QuizQuestion,
)

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Persistent course storage (JSON files in a folder)
# ---------------------------------------------------------------------------

COURSES_DIR = Path(__file__).resolve().parent.parent.parent / "courses"
COURSES_DIR.mkdir(exist_ok=True)

_courses: dict[str, Course] = {}
_step_queues: dict[str, asyncio.Queue[AgentStep | None]] = {}


def _course_path(course_id: str) -> Path:
    return COURSES_DIR / f"{course_id}.json"


def _save_to_disk(course: Course) -> None:
    """Persist a course as a JSON file."""
    try:
        _course_path(course.id).write_text(course.model_dump_json(indent=2))
    except Exception:
        logger.exception("Failed to save course %s to disk", course.id)


def _load_from_disk() -> None:
    """Load all courses from the courses folder into memory."""
    for path in COURSES_DIR.glob("*.json"):
        try:
            course = Course.model_validate_json(path.read_text())
            _courses[course.id] = course
            logger.info("Loaded course %s from %s", course.id, path.name)
        except Exception:
            logger.exception("Failed to load course from %s", path.name)


# Load persisted courses on module import
_load_from_disk()


def get_course(course_id: str) -> Course | None:
    return _courses.get(course_id)


def get_all_courses() -> list[Course]:
    return list(_courses.values())


def store_course(course: Course) -> None:
    _courses[course.id] = course
    _save_to_disk(course)


def create_step_queue(course_id: str) -> asyncio.Queue[AgentStep | None]:
    q: asyncio.Queue[AgentStep | None] = asyncio.Queue()
    _step_queues[course_id] = q
    return q


def get_step_queue(course_id: str) -> asyncio.Queue[AgentStep | None] | None:
    return _step_queues.get(course_id)


def remove_step_queue(course_id: str) -> None:
    _step_queues.pop(course_id, None)


# ---------------------------------------------------------------------------
# LangGraph-powered course generation
# ---------------------------------------------------------------------------

_orchestrator = build_orchestrator_graph().compile()
_writer = build_lesson_writer_graph().compile()
_quiz_gen = build_quiz_generator_graph().compile()
_tutor = build_tutor_graph().compile()


async def run_course_generation(
    course_id: str,
    preferences: CoursePreferences,
    queue: asyncio.Queue[AgentStep | None],
) -> None:
    """Run the full LangGraph orchestrator and stream progress events."""
    try:
        await queue.put(
            AgentStep(type="planning", message="Analyzing topic and planning curriculum...")
        )

        # Run the orchestrator graph (blocking; runs planner + first lesson + quiz)
        result = await asyncio.to_thread(
            _orchestrator.invoke,
            {
                "messages": [],
                "course_preferences": preferences,
                "outline": [],
                "lessons": [],
                "quizzes": [],
                "current_step": "start",
                "validation_result": None,
                "retry_count": 0,
                "student_profile": {},
            },
        )

        outlines = result.get("outline", [])
        lessons = result.get("lessons", [])
        quizzes = result.get("quizzes", [])

        await queue.put(
            AgentStep(
                type="outline_ready",
                message=f"Course outline ready with {len(outlines)} lessons.",
                data={"lesson_count": len(outlines)},
            )
        )

        # Generate remaining lessons on the fly
        for outline in outlines:
            if any(l.index == outline.index for l in lessons):
                continue  # already generated by orchestrator

            await queue.put(
                AgentStep(
                    type="generating_lesson",
                    message=f"Generating lesson: {outline.title}",
                    data={"lesson_index": outline.index, "title": outline.title},
                )
            )

            lesson = await generate_lesson_on_demand(
                outline, preferences, [l.title for l in lessons]
            )
            lessons.append(lesson)

            await queue.put(
                AgentStep(
                    type="lesson_ready",
                    message=f"Lesson ready: {outline.title}",
                    data={"lesson_index": outline.index},
                )
            )

        # Generate remaining quizzes
        for outline in outlines:
            if not outline.has_quiz:
                continue
            if any(q.lesson_index == outline.index for q in quizzes):
                continue

            await queue.put(
                AgentStep(
                    type="generating_quiz",
                    message=f"Generating quiz for lesson {outline.index + 1}",
                    data={"lesson_index": outline.index},
                )
            )

            matching_lesson = next(
                (l for l in lessons if l.index == outline.index), None
            )
            if matching_lesson:
                quiz = await generate_quiz_on_demand(matching_lesson, preferences)
                quizzes.append(quiz)

            await queue.put(
                AgentStep(
                    type="quiz_ready",
                    message=f"Quiz ready for lesson {outline.index + 1}",
                    data={"lesson_index": outline.index},
                )
            )

        # Sort lessons by index; mark first unlocked
        lessons.sort(key=lambda l: l.index)
        if lessons:
            lessons[0] = lessons[0].model_copy(update={"is_unlocked": True})

        course = Course(
            id=course_id,
            title=f"Course: {preferences.topic}",
            description=(
                f"A {preferences.course_length} {preferences.level} course "
                f"on {preferences.topic}."
            ),
            topic=preferences.topic,
            level=preferences.level,
            lessons=lessons,
            quizzes=quizzes,
        )
        store_course(course)

        await queue.put(
            AgentStep(
                type="complete",
                message="Course generation complete!",
                data={"course_id": course_id},
            )
        )
    except Exception as e:
        await queue.put(AgentStep(type="error", message=str(e)))
    finally:
        await queue.put(None)


# ---------------------------------------------------------------------------
# On-demand generation helpers
# ---------------------------------------------------------------------------


async def generate_lesson_on_demand(
    outline: LessonOutline,
    preferences: CoursePreferences,
    previous_titles: list[str] | None = None,
) -> Lesson:
    """Invoke the lesson writer graph for a single lesson."""
    result = await asyncio.to_thread(
        _writer.invoke,
        {
            "messages": [],
            "outline": outline,
            "course_preferences": preferences,
            "previous_lesson_titles": previous_titles or [],
            "draft_content": "",
            "interactive_elements": [],
            "validation_result": None,
            "retry_count": 0,
            "lesson": None,
        },
    )
    lesson: Lesson | None = result.get("lesson")
    if lesson:
        return lesson
    # Fallback
    return Lesson(
        **outline.model_dump(),
        content=f"# {outline.title}\n\nContent generation in progress.",
        is_unlocked=False,
    )


async def generate_quiz_on_demand(
    lesson: Lesson, preferences: CoursePreferences
) -> Quiz:
    """Invoke the quiz generator graph for a single lesson."""
    result = await asyncio.to_thread(
        _quiz_gen.invoke,
        {
            "messages": [],
            "lesson": lesson,
            "course_preferences": preferences,
            "key_concepts": lesson.key_topics,
            "questions": [],
            "validation_result": None,
            "retry_count": 0,
            "quiz": None,
        },
    )
    quiz: Quiz | None = result.get("quiz")
    if quiz:
        return quiz
    # Fallback
    return Quiz(
        lesson_index=lesson.index,
        questions=[
            QuizQuestion(
                id=f"fallback-{lesson.index}-0",
                question=f"What is a key concept from {lesson.title}?",
                question_type="short-answer",
                correct_answer=lesson.key_topics[0] if lesson.key_topics else "N/A",
                explanation="Review the lesson for the answer.",
            )
        ],
    )


async def run_tutor_check(
    course_id: str,
    quiz_scores: list[float],
    student_profile: dict[str, Any],
) -> dict[str, Any]:
    """Invoke the tutor agent to generate feedback + adaptations."""
    result = await asyncio.to_thread(
        _tutor.invoke,
        {
            "messages": [],
            "student_profile": student_profile,
            "quiz_scores": quiz_scores,
            "assessment": None,
            "action_plan": None,
            "feedback": "",
            "adaptations": {},
        },
    )
    return {
        "feedback": result.get("feedback", "Keep going!"),
        "adaptations": result.get("adaptations", {}),
    }


# ---------------------------------------------------------------------------
# Quiz grading
# ---------------------------------------------------------------------------


def grade_quiz_answers(quiz: Quiz, answers: dict[str, str]) -> dict[str, Any]:
    """Grade user answers against a quiz. Returns scoring details."""
    results = []
    correct_count = 0

    for q in quiz.questions:
        user_answer = answers.get(q.id, "")
        is_correct = user_answer.strip().lower() == q.correct_answer.strip().lower()
        if is_correct:
            correct_count += 1
        results.append(
            {
                "question_id": q.id,
                "correct": is_correct,
                "user_answer": user_answer,
                "correct_answer": q.correct_answer,
                "explanation": q.explanation,
            }
        )

    total = len(quiz.questions)
    return {
        "score": correct_count / total if total > 0 else 0.0,
        "total_questions": total,
        "correct_count": correct_count,
        "results": results,
    }
